A minimal-ish example show that coverage does not work with requirejs
To run it, use `karma start karma.conf.coffee` .

The error message will contain this:

```
➜  coffee-requirejs git:(master) ✗ karma start karma.conf.coffee
...
20 08 2015 15:56:19.739:WARN [web-server]: 404: /base/calculator.js
Firefox 39.0.0 (Mac OS X 10.10.0) ERROR: 'There is no timestamp for
/base/calculator.js!'
Firefox 39.0.0 (Mac OS X 10.10.0) ERROR
  Error: Script error for: calculator
    http://requirejs.org/docs/errors.html#scripterror
...
```

Notice the `404` for `/base/calculator.js` . This is because the
filename is actually `/base/calculator.coffee`. The real Karma
CoffeeScript preprocessor will change the extension of the compiled
file to `.js`